export interface Record {
    id: number;
    name: string;
    score: number;
}

export const RECORDS: Record[] = [{
    id: 1,
    name: "Garen",
    score: 4162
}, {
    id: 2,
    name: "Imanol",
    score: 656
}, {
    id: 3,
    name: "Brunihild",
    score: 4091
}, {
    id: 4,
    name: "Voestaa'e",
    score: 3715
}, {
    id: 5,
    name: "Gertrude",
    score: 6790
}, {
    id: 6,
    name: "Austra",
    score: 8194
}, {
    id: 7,
    name: "Aneta",
    score: 1281
}, {
    id: 8,
    name: "Jörgen",
    score: 7822
}, {
    id: 9,
    name: "Terje",
    score: 999
}, {
    id: 10,
    name: "Naveen",
    score: 6221
}, {
    id: 11,
    name: "Steph",
    score: 7968
}, {
    id: 12,
    name: "Israfil",
    score: 5526
}, {
    id: 13,
    name: "Garrett",
    score: 2414
}, {
    id: 14,
    name: "Yami",
    score: 4723
}, {
    id: 15,
    name: "Tena",
    score: 6707
}, {
    id: 16,
    name: "Milada",
    score: 4462
}, {
    id: 17,
    name: "Livia",
    score: 9426
}, {
    id: 18,
    name: "Egnatius",
    score: 5297
}, {
    id: 19,
    name: "Colmán",
    score: 7866
}, {
    id: 20,
    name: "Hefina",
    score: 9880
}];